services:
  frontend: 
    build:
      context: .  
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore: 
            - node_modules